In [87]:
import pandas as pd
import numpy as np

data = {
    'Emp_ID': [1, 2, 3, 4, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    'Name': ['Alice ', 'BOB', 'charles_smith', 'dana_white', 'dana_white', 'Edward', '  Fiona', 'George', 'Hannah', 'Ian', 'Jack', 'Kelly', 'Liam', 'Mona', 'Noah', 'Olivia', 'Peter', 'Quinn', 'Rose', 'Sam', 'Tina', 'Uma', 'Victor', 'Wendy', 'Xavier', 'Yara', 'Zane', 'Adam', 'Bella', 'Chris', 'Daisy', 'Ethan', 'Flora', 'Gabe', 'Hope', 'Ivan', 'Jade', 'Karl', 'Luna', 'Milo', 'Nora', 'Otis', 'Pia', 'Reed', 'Sia', 'Toby', 'Uriel', 'Vera', 'Will', 'Xena'],
    'Join_Date': ['2020-01-01', '2020/05/12', 'Jan-10-2021', '2021-02-15', '2021-02-15', '2026-12-01', '2019-11-30', None, '2022.01.01', '15-08-2021', '2020-01-01', '2021-03-04', '2021-05-06', '2022-07-08', '2020-09-10', '2021-11-12', '2022-01-14', '2020-03-16', '2021-05-18', '2022-07-20', '2020-09-22', '2021-11-24', '2022-01-26', '2020-03-28', '2021-05-30', '2022-08-01', '2020-10-03', '2021-12-05', '2022-02-07', '2020-04-09', '2021-06-11', '2022-08-13', '2020-10-15', '2021-12-17', '2022-02-19', '2020-04-21', '2021-06-23', '2022-08-25', '2020-10-27', '2021-12-29', '2022-03-02', '2020-05-04', '2021-07-06', '2022-09-08', '2020-11-10', '2021-01-12', '2022-03-14', '2020-05-16', '2021-07-18', '2022-09-20'],
    'Salary': ['$50,000', '60000', '$55,000', '45k', '45k', '70,000', '$80,000', 'NA', '$62000', '58,000', '50,000', '52000', '54000', '56000', '58000', '60000', '62000', '64000', '66000', '68000', '70000', '72000', '74000', '76000', '78000', '80000', '82000', '84000', '86000', '88000', '90000', '92000', '94000', '96000', '98000', '100000', '102000', '104000', '106000', '108000', '110000', '112000', '114000', '116000', '118000', '120000', '122000', '124000', '126000', '128000'],
    'Department': ['IT', 'it', 'I.T.', 'Human Resources', 'HR', 'HR', 'Finance', 'FIN', 'Sales', 'sales', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR', 'IT', 'Finance', 'Sales', 'HR'],
    'Phone': ['123-456-7890', '1234567890', '987.654.3210', '555-000-1111', '555-000-1111', None, '111-222-3333', '4445556666', '777-888-9999', '000-111-2222', '123-456-7890', '123-456-7891', '123-456-7892', '123-456-7893', '123-456-7894', '123-456-7895', '123-456-7896', '123-456-7897', '123-456-7898', '123-456-7899', '123-456-7900', '123-456-7901', '123-456-7902', '123-456-7903', '123-456-7904', '123-456-7905', '123-456-7906', '123-456-7907', '123-456-7908', '123-456-7909', '123-456-7910', '123-456-7911', '123-456-7912', '123-456-7913', '123-456-7914', '123-456-7915', '123-456-7916', '123-456-7917', '123-456-7918', '123-456-7919', '123-456-7920', '123-456-7921', '123-456-7922', '123-456-7923', '123-456-7924', '123-456-7925', '123-456-7926', '123-456-7927', '123-456-7928', '123-456-7929'],
    'Performance_Score': [85, 90, 78, 92, 92, 250, 88, 70, -5, 80, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 85, 86, 87, 88, 89, 90, 91, 92],
    'Remote_Worker': ['Yes', 'no', 'YES', 'No', 'No', 'Yes', 'y', 'n', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'],
    'Email': ['alice@company.com', 'bob@comp.com', 'charles@smith.com', 'dana@white.com', 'dana@white.com', 'edward@co.com', 'fiona@firm.com', 'george@mail.com', 'hannah@web.com', 'ian@net.com', 'jack@company.com', 'kelly@company.com', 'liam@company.com', 'mona@company.com', 'noah@company.com', 'olivia@company.com', 'peter@company.com', 'quinn@company.com', 'rose@company.com', 'sam@company.com', 'tina@company.com', 'uma@company.com', 'victor@company.com', 'wendy@company.com', 'xavier@company.com', 'yara@company.com', 'zane@company.com', 'adam@company.com', 'bella@company.com', 'chris@company.com', 'daisy@company.com', 'ethan@company.com', 'flora@company.com', 'gabe@company.com', 'hope@company.com', 'ivan@company.com', 'jade@company.com', 'karl@company.com', 'luna@company.com', 'milo@company.com', 'nora@company.com', 'otis@company.com', 'pia@company.com', 'reed@company.com', 'sia@company.com', 'toby@company.com', 'uriel@company.com', 'vera@company.com', 'will@company.com', 'xena@company.com'],
    'Address': ['123 Maple St', '456 Oak Ave', '789 Pine Rd', '101 Cedar Ln', '101 Cedar Ln', '202 Birch Blvd', '303 Spruce Ct', '404 Ash Dr', '505 Willow Way', '606 Elm St', '123 Maple St', '707 Poplar Dr', '808 Cherry Ln', '909 Walnut St', '111 Chestnut Ave', '222 Hickory Rd', '333 Linden Ln', '444 Sycamore Blvd', '555 Magnolia Ct', '666 Cypress Dr', '777 Alder Way', '888 Redwood St', '999 Sequoia Dr', '111 Juniper Ln', '222 Acacia Ave', '333 Banyan Rd', '444 Baobab St', '555 Bonsai Blvd', '666 Boxwood Ct', '777 Catalpa Dr', '888 Dogwood Way', '999 Ginkgo St', '111 Hemlock Ln', '222 Holly Ave', '333 Ironwood Rd', '444 Kapok Blvd', '555 Laurel Ct', '666 Mimosa Dr', '777 Olive Way', '888 Palm St', '999 Quince Dr', '111 Rosewood Ln', '222 Sassafras Ave', '333 Teak Rd', '444 Upas Blvd', '555 Vine Ct', '666 Wisteria Dr', '777 Yew Way', '888 Zelkova St', '999 Arbutus Dr']
}

df = pd.DataFrame(data)

In [88]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,BOB,2020/05/12,60000,it,1234567890,90,no,bob@comp.com,456 Oak Ave
2,3,charles_smith,Jan-10-2021,"$55,000",I.T.,987.654.3210,78,YES,charles@smith.com,789 Pine Rd
3,4,dana_white,2021-02-15,45k,Human Resources,555-000-1111,92,No,dana@white.com,101 Cedar Ln
4,4,dana_white,2021-02-15,45k,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln

In [89]:
df.isnull().sum()

Emp_ID               0
Name                 0
Join_Date            1
Salary               0
Department           0
Phone                1
Performance_Score    0
Remote_Worker        0
Email                0
Address              0
dtype: int64

In [90]:
df.describe()

          Emp_ID  Performance_Score
count  50.000000          50.000000
mean   25.480000          91.760000
std    14.606736          27.139519
min     1.000000          -5.000000
25%    13.250000          87.000000
50%    25.500000          90.500000
75%    37.750000          94.750000
max    50.000000         250.000000

In [91]:
df["Emp_ID"].unique()

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [92]:
df["Emp_ID"].duplicated().sum()

np.int64(1)

In [93]:
df.shape

(50, 10)

In [94]:
df.drop_duplicates(subset=["Emp_ID"] ,keep="first",inplace=True)

In [95]:
df["Emp_ID"].duplicated().sum()

np.int64(0)

In [96]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,BOB,2020/05/12,60000,it,1234567890,90,no,bob@comp.com,456 Oak Ave
2,3,charles_smith,Jan-10-2021,"$55,000",I.T.,987.654.3210,78,YES,charles@smith.com,789 Pine Rd
3,4,dana_white,2021-02-15,45k,Human Resources,555-000-1111,92,No,dana@white.com,101 Cedar Ln
5,6,Edward,2026-12-01,"70,000",HR,None,250,Yes,edward@co.com,202 Birch Blvd

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 0 to 49
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             49 non-null     int64
 1   Name               49 non-null     object
 2   Join_Date          48 non-null     object
 3   Salary             49 non-null     object
 4   Department         49 non-null     object
 5   Phone              48 non-null     object
 6   Performance_Score  49 non-null     int64
 7   Remote_Worker      49 non-null     object
 8   Email              49 non-null     object
 9   Address            49 non-null     object
dtypes: int64(2), object(8)
memory usage: 4.2+ KB

In [98]:
df["Name"]= df["Name"].str.strip().str.title()

In [99]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,Bob,2020/05/12,60000,it,1234567890,90,no,bob@comp.com,456 Oak Ave
2,3,Charles_Smith,Jan-10-2021,"$55,000",I.T.,987.654.3210,78,YES,charles@smith.com,789 Pine Rd
3,4,Dana_White,2021-02-15,45k,Human Resources,555-000-1111,92,No,dana@white.com,101 Cedar Ln
5,6,Edward,2026-12-01,"70,000",HR,None,250,Yes,edward@co.com,202 Birch Blvd

In [100]:
df.isnull().sum()

Emp_ID               0
Name                 0
Join_Date            1
Salary               0
Department           0
Phone                1
Performance_Score    0
Remote_Worker        0
Email                0
Address              0
dtype: int64

In [101]:
df.dropna(subset=['Join_Date', 'Phone'], inplace=True)

In [102]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,Bob,2020/05/12,60000,it,1234567890,90,no,bob@comp.com,456 Oak Ave
2,3,Charles_Smith,Jan-10-2021,"$55,000",I.T.,987.654.3210,78,YES,charles@smith.com,789 Pine Rd
3,4,Dana_White,2021-02-15,45k,Human Resources,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,"$80,000",Finance,111-222-3333,88,y,fiona@firm.com,303 Spruce Ct

In [103]:
df.isnull().sum()

Emp_ID               0
Name                 0
Join_Date            0
Salary               0
Department           0
Phone                0
Performance_Score    0
Remote_Worker        0
Email                0
Address              0
dtype: int64

In [104]:
df["Department"].unique()

array(['IT', 'it', 'I.T.', 'Human Resources', 'Finance', 'Sales', 'sales',
       'HR'], dtype=object)

In [105]:
dept={
    'it':'IT',
    'I.T.':'IT',
    'Human Resources':'HR',
    'sales':'Sales'
}
df['Department'] = df['Department'].replace(dept)

In [106]:
df["Department"].unique()

array(['IT', 'HR', 'Finance', 'Sales'], dtype=object)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, 0 to 49
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             47 non-null     int64
 1   Name               47 non-null     object
 2   Join_Date          47 non-null     object
 3   Salary             47 non-null     object
 4   Department         47 non-null     object
 5   Phone              47 non-null     object
 6   Performance_Score  47 non-null     int64
 7   Remote_Worker      47 non-null     object
 8   Email              47 non-null     object
 9   Address            47 non-null     object
dtypes: int64(2), object(8)
memory usage: 4.0+ KB

In [108]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,Bob,2020/05/12,60000,IT,1234567890,90,no,bob@comp.com,456 Oak Ave
2,3,Charles_Smith,Jan-10-2021,"$55,000",IT,987.654.3210,78,YES,charles@smith.com,789 Pine Rd
3,4,Dana_White,2021-02-15,45k,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,"$80,000",Finance,111-222-3333,88,y,fiona@firm.com,303 Spruce Ct

In [109]:
df['Remote_Worker'].unique()

array(['Yes', 'no', 'YES', 'No', 'y'], dtype=object)

In [110]:
dict={
    "no":"No",
    "y":"Yes",
    "YES":"Yes",
    "NO":"No"
}
df['Remote_Worker'] = df['Remote_Worker'].replace(dict)

In [111]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,Bob,2020/05/12,60000,IT,1234567890,90,No,bob@comp.com,456 Oak Ave
2,3,Charles_Smith,Jan-10-2021,"$55,000",IT,987.654.3210,78,Yes,charles@smith.com,789 Pine Rd
3,4,Dana_White,2021-02-15,45k,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,"$80,000",Finance,111-222-3333,88,Yes,fiona@firm.com,303 Spruce Ct

In [112]:
df['Join_Date'].unique()

array(['2020-01-01', '2020/05/12', 'Jan-10-2021', '2021-02-15',
       '2019-11-30', '2022.01.01', '15-08-2021', '2021-03-04',
       '2021-05-06', '2022-07-08', '2020-09-10', '2021-11-12',
       '2022-01-14', '2020-03-16', '2021-05-18', '2022-07-20',
       '2020-09-22', '2021-11-24', '2022-01-26', '2020-03-28',
       '2021-05-30', '2022-08-01', '2020-10-03', '2021-12-05',
       '2022-02-07', '2020-04-09', '2021-06-11', '2022-08-13',
       '2020-10-15', '2021-12-17', '2022-02-19', '2020-04-21',
       '2021-06-23', '2022-08-25', '2020-10-27', '2021-12-29',
       '2022-03-02', '2020-05-04', '2021-07-06', '2022-09-08',
       '2020-11-10', '2021-01-12', '2022-03-14', '2020-05-16',
       '2021-07-18', '2022-09-20'], dtype=object)

In [113]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')

# Now all dates look like YYYY-MM-DD
print(df['Join_Date'].head())

0   2020-01-01
1          NaT
2          NaT
3   2021-02-15
6   2019-11-30
Name: Join_Date, dtype: datetime64[ns]

In [114]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
1,2,Bob,NaT,60000,IT,1234567890,90,No,bob@comp.com,456 Oak Ave
2,3,Charles_Smith,NaT,"$55,000",IT,987.654.3210,78,Yes,charles@smith.com,789 Pine Rd
3,4,Dana_White,2021-02-15,45k,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,"$80,000",Finance,111-222-3333,88,Yes,fiona@firm.com,303 Spruce Ct

In [115]:
df.dropna(subset=['Join_Date'], inplace=True)

print(f"Rows remaining: {len(df)}")

Rows remaining: 43

In [116]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,"$50,000",IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
3,4,Dana_White,2021-02-15,45k,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,"$80,000",Finance,111-222-3333,88,Yes,fiona@firm.com,303 Spruce Ct
10,11,Jack,2020-01-01,"50,000",IT,123-456-7890,85,Yes,jack@company.com,123 Maple St
11,12,Kelly,2021-03-04,52000,Finance,123-456-7891,86,No,kelly@company.com,707 Poplar Dr

In [117]:
# 1. Make everything lowercase so '45K' and '45k' both work
df['Salary'] = df['Salary'].astype(str).str.lower()

# 2. Replace 'k' with '000'
df['Salary'] = df['Salary'].str.replace('k', '000', regex=False)

# 3. Remove other non-numeric symbols (like $ and ,)
df['Salary'] = df['Salary'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)

# 4. Final conversion to numeric
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

In [118]:
df.head()

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,50000,IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
3,4,Dana_White,2021-02-15,45000,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,80000,Finance,111-222-3333,88,Yes,fiona@firm.com,303 Spruce Ct
10,11,Jack,2020-01-01,50000,IT,123-456-7890,85,Yes,jack@company.com,123 Maple St
11,12,Kelly,2021-03-04,52000,Finance,123-456-7891,86,No,kelly@company.com,707 Poplar Dr

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, 0 to 49
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             43 non-null     int64
 1   Name               43 non-null     object
 2   Join_Date          43 non-null     datetime64[ns]
 3   Salary             43 non-null     int64
 4   Department         43 non-null     object
 5   Phone              43 non-null     object
 6   Performance_Score  43 non-null     int64
 7   Remote_Worker      43 non-null     object
 8   Email              43 non-null     object
 9   Address            43 non-null     object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 3.7+ KB

In [120]:
df['Phone'].unique()

array(['123-456-7890', '555-000-1111', '111-222-3333', '123-456-7891',
       '123-456-7892', '123-456-7893', '123-456-7894', '123-456-7895',
       '123-456-7896', '123-456-7897', '123-456-7898', '123-456-7899',
       '123-456-7900', '123-456-7901', '123-456-7902', '123-456-7903',
       '123-456-7904', '123-456-7905', '123-456-7906', '123-456-7907',
       '123-456-7908', '123-456-7909', '123-456-7910', '123-456-7911',
       '123-456-7912', '123-456-7913', '123-456-7914', '123-456-7915',
       '123-456-7916', '123-456-7917', '123-456-7918', '123-456-7919',
       '123-456-7920', '123-456-7921', '123-456-7922', '123-456-7923',
       '123-456-7924', '123-456-7925', '123-456-7926', '123-456-7927',
       '123-456-7928', '123-456-7929'], dtype=object)

In [121]:
df.describe()

,Emp_ID,Join_Date,Salary,Performance_Score
count,43.000000,43,43.000000,43.000000
mean,28.651163,2021-05-27 22:19:32.093023232,86860.465116,91.465116
min,1.000000,2019-11-30 00:00:00,45000.000000,85.000000
25%,18.500000,2020-09-27 12:00:00,67000.000000,88.000000
50%,29.000000,2021-06-11 00:00:00,86000.000000,91.000000
75%,39.500000,2022-02-01 00:00:00,107000.000000,95.000000
max,50.000000,2022-09-20 00:00:00,128000.000000,100.000000
std,13.190696,NaN,24231.602148,4.579191

In [122]:
df

,Emp_ID,Name,Join_Date,Salary,Department,Phone,Performance_Score,Remote_Worker,Email,Address
0,1,Alice,2020-01-01,50000,IT,123-456-7890,85,Yes,alice@company.com,123 Maple St
3,4,Dana_White,2021-02-15,45000,HR,555-000-1111,92,No,dana@white.com,101 Cedar Ln
6,7,Fiona,2019-11-30,80000,Finance,111-222-3333,88,Yes,fiona@firm.com,303 Spruce Ct
10,11,Jack,2020-01-01,50000,IT,123-456-7890,85,Yes,jack@company.com,123 Maple St
11,12,Kelly,2021-03-04,52000,Finance,123-456-7891,86,No,kelly@company.com,707 Poplar Dr
12,13,Liam,2021-05-06,54000,Sales,123-456-7892,87,Yes,liam@company.com,808 Cherry Ln
13,14,Mona,2022-07-08,56000,HR,123-456-7893,88,No,mona@company.com,909 Walnut St
14,15,Noah,2020-09-10,58000,IT,123-456-7894,89,Yes,noah@company.com,111 Chestnut Ave
15,16,Olivia,2021-11-12,60000,Finance,123-456-7895,90,No,olivia@company.com,222 Hickory Rd
16,17,Peter,2022-01-14,62000,Sales,123-456-7896,91,Yes,peter@company.com,333 Linden Ln
17,18,Quinn,2020-03-16,64000,HR,123-456-7897,92,No,quinn@company.com,444 Sycamore Blvd
18,19,Rose,2021-05-18,66000,IT,123-456-7898,93,Yes,rose@company.com,555 Magnolia Ct
19,20,Sam,2022-07-20,68000,Finance,123-456-7899,94,No,sam@company.com,666 Cypress Dr
20,21,Tina,2020-09-22,70000,Sales,123-456-7900,95,Yes,tina@company.com,777 Alder Way
21,22,Uma,2021-11-24,72000,HR,123-456-7901,96,No,uma@company.com,888 Redwood St
22,23,Victor,2022-01-26,74000,IT,123-456-7902,97,Yes,victor@company.com,999 Sequoia Dr
23,24,Wendy,2020-03-28,76000,Finance,123-456-7903,98,No,wendy@company.com,111 Juniper Ln
24,25,Xavier,2021-05-30,78000,Sales,123-456-7904,99,Yes,xavier@company.com,222 Acacia Ave
25,26,Yara,2022-08-01,80000,HR,123-456-7905,100,No,yara@company.com,333 Banyan Rd
26,27,Zane,2020-10-03,82000,IT,123-456-7906,85,Yes,zane@company.com,444 Baobab St
27,28,Adam,2021-12-05,84000,Finance,123-456-7907,86,No,adam@company.com,555 Bonsai Blvd
28,29,Bella,2022-02-07,86000,Sales,123-456-7908,87,Yes,bella@company.com,666 Boxwood Ct
29,30,Chris,2020-04-09,88000,HR,123-456-7909,88,No,chris@company.com,777 Catalpa Dr
30,31,Daisy,2021-06-11,90000,IT,123-456-7910,89,Yes,daisy@company.com,888 Dogwood Way
31,32,Ethan,2022-08-13,92000,Finance,123-456-7911,90,No,ethan@company.com,999 Ginkgo St
32,33,Flora,2020-10-15,94000,Sales,123-456-7912,91,Yes,flora@company.com,111 Hemlock Ln
33,34,Gabe,2021-12-17,96000,HR,123-456-7913,92,No,gabe@company.com,222 Holly Ave
34,35,Hope,2022-02-19,98000,IT,123-456-7914,93,Yes,hope@company.com,333 Ironwood Rd
35,36,Ivan,2020-04-21,100000,Finance,123-456-7915,94,No,ivan@company.com,444 Kapok Blvd
36,37,Jade,2021-06-23,102000,Sales,123-456-7916,95,Yes,jade@company.com,555 Laurel Ct
37,38,Karl,2022-08-25,104000,HR,123-456-7917,96,No,karl@company.com,666 Mimosa Dr
38,39,Luna,2020-10-27,106000,IT,123-456-7918,97,Yes,luna@company.com,777 Olive Way
39,40,Milo,2021-12-29,108000,Finance,123-456-7919,98,No,milo@company.com,888 Palm St
40,41,Nora,2022-03-02,110000,Sales,123-456-7920,99,Yes,nora@company.com,999 Quince Dr
41,42,Otis,2020-05-04,112000,HR,123-456-7921,100,No,otis@company.com,111 Rosewood Ln
42,43,Pia,2021-07-06,114000,IT,123-456-7922,85,Yes,pia@company.com,222 Sassafras Ave
43,44,Reed,2022-09-08,116000,Finance,123-456-7923,86,No,reed@company.com,333 Teak Rd
44,45,Sia,2020-11-10,118000,Sales,123-456-7924,87,Yes,sia@company.com,444 Upas Blvd
45,46,Toby,2021-01-12,120000,HR,123-456-7925,88,No,toby@company.com,555 Vine Ct
46,47,Uriel,2022-03-14,122000,IT,123-456-7926,89,Yes,uriel@company.com,666 Wisteria Dr
47,48,Vera,2020-05-16,124000,Finance,123-456-7927,90,No,vera@company.com,777 Yew Way
48,49,Will,2021-07-18,126000,Sales,123-456-7928,91,Yes,will@company.com,888 Zelkova St
49,50,Xena,2022-09-20,128000,HR,123-456-7929,92,No,xena@company.com,999 Arbutus Dr

In [123]:
df['Performance_Score'].min()

np.int64(85)