In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name":["joe","brunie","wick"],
    "Age":[34,45,23],
    "Sex":["M","M","M"],
    "salary":[3400,3901,4658]
},index=['a','b','c'])

df

     Name  Age Sex  salary
a     joe   34   M    3400
b  brunie   45   M    3901
c    wick   23   M    4658

In [3]:
df[["Age","Sex"]] #to see the data of particular column

   Age Sex
a   34   M
b   45   M
c   23   M

In [4]:
row = df.loc['b']
row

Name      brunie
Age           45
Sex            M
salary      3901
Name: b, dtype: object

In [5]:
max_age=df["Age"].max()
max_age

np.int64(45)

In [6]:
min_age=df["Age"].min()
max_age

np.int64(45)

In [7]:
min_age=df[["Age","Sex"]].min()
max_age

np.int64(45)

In [8]:
df.describe()

        Age       salary
count   3.0     3.000000
mean   34.0  3986.333333
std    11.0   633.326403
min    23.0  3400.000000
25%    28.5  3650.500000
50%    34.0  3901.000000
75%    39.5  4279.500000
max    45.0  4658.000000

In [9]:
df["Dep"] = ["web","node","bde"]
print(df)

     Name  Age Sex  salary   Dep
a     joe   34   M    3400   web
b  brunie   45   M    3901  node
c    wick   23   M    4658   bde

In [10]:
details_dataset = pd.read_csv("data/Details.csv")
print(details_dataset)

     Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0     B-25681    1096     658         7  Electronics  Electronic Games
1     B-26055    5729      64        14    Furniture            Chairs
2     B-25955    2927     146         8    Furniture         Bookcases
3     B-26093    2847     712         8  Electronics          Printers
4     B-25602    2617    1151         4  Electronics            Phones
...       ...     ...     ...       ...          ...               ...
1495  B-25700       7      -3         2     Clothing       Hankerchief
1496  B-25757    3151     -35         7     Clothing          Trousers
1497  B-25973    4141    1698        13  Electronics          Printers
1498  B-25698       7      -2         1     Clothing       Hankerchief
1499  B-25993    4363     305         5    Furniture            Tables

      PaymentMode
0             COD
1             EMI
2             EMI
3     Credit Card
4     Credit Card
...           ...
1495          COD
1496          EMI
1497          COD
1498          COD
1499          EMI

[1500 rows x 7 columns]

In [11]:
print(details_dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB
None

In [12]:
details_dataset.head(10)
#use to fetch a particular number of rows from the dataset 
#accept a number as parameter and their default value is 5 if we dont not pass any value

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
5,B-25881,2244,247,4,Clothing,Trousers,Credit Card
6,B-25696,275,-275,4,Clothing,Saree,COD
7,B-25687,387,-213,5,Clothing,Saree,UPI
8,B-25643,50,-44,2,Clothing,Hankerchief,UPI
9,B-25851,135,-54,5,Clothing,Kurti,COD

In [13]:
details_dataset.tail(10)
#give the bottom n rows

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
1490,B-25858,2457,665,11,Electronics,Electronic Games,EMI
1491,B-25697,4,-3,1,Clothing,Skirt,Credit Card
1492,B-25798,2830,-1981,13,Furniture,Bookcases,EMI
1493,B-25873,7,1,1,Clothing,Hankerchief,COD
1494,B-25740,7,0,2,Clothing,Skirt,COD
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [14]:
amount = details_dataset['Amount'] #for fetching the data from a particular column, can accept mutiple values in list[[col1,col2,....colN]]
print(amount)

0       1096
1       5729
2       2927
3       2847
4       2617
        ...
1495       7
1496    3151
1497    4141
1498       7
1499    4363
Name: Amount, Length: 1500, dtype: int64

In [15]:
print(type(amount))
print(type(details_dataset['Amount']))
#type is used ti check the type of paticular column

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [16]:
print(details_dataset["Amount"].dtype) 
#for check the which type of data a series can store

int64

In [17]:
print(details_dataset['Amount'].shape)
#for check the actual entries in the datasets

(1500,)

In [18]:
type(details_dataset[["Amount", "Category"]])

pandas.core.frame.DataFrame

In [19]:
details_dataset[["Amount", "Category"]].shape 
#it give the output like total no. of rows and column (rows,column)

(1500, 2)

In [20]:
above_five_data = details_dataset[details_dataset["Quantity"] > 6]
above_five_data.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
10,B-25703,231,-190,9,Clothing,Hankerchief,COD

In [21]:
cod = details_dataset[details_dataset["PaymentMode"] == "COD"]
cod.head(7)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
6,B-25696,275,-275,4,Clothing,Saree,COD
9,B-25851,135,-54,5,Clothing,Kurti,COD
10,B-25703,231,-190,9,Clothing,Hankerchief,COD
23,B-25845,82,-33,4,Clothing,Kurti,COD
31,B-25816,391,113,8,Clothing,Stole,COD
44,B-25779,1361,980,3,Furniture,Tables,COD

In [22]:
# 1. Add parentheses around each condition
#filtering process
cond = (details_dataset["Quantity"] > 5) & (details_dataset["PaymentMode"] == "COD")

# 2. Apply the filter
result = details_dataset[cond]
result.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
10,B-25703,231,-190,9,Clothing,Hankerchief,COD
31,B-25816,391,113,8,Clothing,Stole,COD
81,B-25666,934,-916,7,Electronics,Electronic Games,COD
82,B-25675,929,-93,9,Clothing,Saree,COD

In [23]:
result = details_dataset.query("Quantity > 10 and PaymentMode == 'COD' and Category =='Clothing'")
result

    Order ID  Amount  Profit  Quantity  Category Sub-Category PaymentMode
155  B-26019     585     175        13  Clothing      T-shirt         COD
310  B-25745     296     225        11  Clothing        Saree         COD
314  B-26035     291     119        11  Clothing        Saree         COD
428  B-26055     213       4        14  Clothing        Shirt         COD

In [24]:
max = details_dataset[['Amount','Quantity']].max() #used to find min and max 
print(max)

Amount      5729
Quantity      14
dtype: int64

In [25]:
modes = ["COD", "Debit Card", "UPI",]
cond = details_dataset["PaymentMode"].isin(modes)

details_dataset[cond].tail(20)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
1467,B-25752,8,-2,2,Clothing,Hankerchief,COD
1468,B-25656,1389,680,7,Clothing,Saree,COD
1469,B-25748,8,-1,2,Clothing,Leggings,COD
1470,B-25758,8,-2,1,Clothing,Stole,COD
1471,B-25950,13,4,1,Clothing,Leggings,UPI
1472,B-25707,8,-6,1,Clothing,Stole,COD
1474,B-25955,1716,309,7,Electronics,Accessories,COD
1477,B-25686,332,503,3,Electronics,Printers,COD
1478,B-25655,7,-4,3,Clothing,Hankerchief,COD
1480,B-25862,2061,701,5,Furniture,Bookcases,UPI
1482,B-25823,2103,322,8,Electronics,Electronic Games,UPI
1483,B-25881,2115,23,5,Furniture,Chairs,COD
1484,B-25910,850,-289,5,Electronics,Electronic Games,COD
1487,B-25997,2292,127,7,Furniture,Bookcases,COD
1489,B-25969,2452,191,7,Furniture,Bookcases,UPI
1493,B-25873,7,1,1,Clothing,Hankerchief,COD
1494,B-25740,7,0,2,Clothing,Skirt,COD
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD

In [26]:
age_no_na = details_dataset[details_dataset["Profit"].notna()]
age_no_na

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

loc is used to select a specify row

In [27]:
row_1 = details_dataset.iloc[0]
row_1

Order ID                 B-25681
Amount                      1096
Profit                       658
Quantity                       7
Category             Electronics
Sub-Category    Electronic Games
PaymentMode                  COD
Name: 0, dtype: object

In [28]:
row_100 = details_dataset.loc[10]
row_100

Order ID            B-25703
Amount                  231
Profit                 -190
Quantity                  9
Category           Clothing
Sub-Category    Hankerchief
PaymentMode             COD
Name: 10, dtype: object

In [29]:
#for selecting multiple rows[[]]
rows = details_dataset.loc[[0,10]]
rows

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
10,B-25703,231,-190,9,Clothing,Hankerchief,COD

In [30]:
list_1 = [10,123]
rows = details_dataset.loc[list_1]
rows

    Order ID  Amount  Profit  Quantity  Category Sub-Category PaymentMode
10   B-25703     231    -190         9  Clothing  Hankerchief         COD
123  B-25808      63     -17         6  Clothing     Leggings         COD

In [31]:
details_dataset.iloc[2:5 , 1:4]

   Amount  Profit  Quantity
2    2927     146         8
3    2847     712         8
4    2617    1151         4

In [32]:
#renaming the column name
details_dataset.rename(columns={"Order ID" :"Order_Id"}, inplace=True)
details_dataset

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [33]:
details_dataset.isnull().head()
details_dataset.dropna(axis=0) # drop a row that contains any null value 
# details_dataset.drop(details_dataset.iloc[0])

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [34]:
details_dataset["Category"] = details_dataset["Category"].apply(lambda x: x.upper())
details_dataset

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,ELECTRONICS,Electronic Games,COD
1,B-26055,5729,64,14,FURNITURE,Chairs,EMI
2,B-25955,2927,146,8,FURNITURE,Bookcases,EMI
3,B-26093,2847,712,8,ELECTRONICS,Printers,Credit Card
4,B-25602,2617,1151,4,ELECTRONICS,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,CLOTHING,Hankerchief,COD
1496,B-25757,3151,-35,7,CLOTHING,Trousers,EMI
1497,B-25973,4141,1698,13,ELECTRONICS,Printers,COD
1498,B-25698,7,-2,1,CLOTHING,Hankerchief,COD
1499,B-25993,4363,305,5,FURNITURE,Tables,EMI

In [35]:
#creating a total_amount column
details_dataset["Total"] = details_dataset["Amount"] * details_dataset["Quantity"]
details_dataset.head()

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Total
0,B-25681,1096,658,7,ELECTRONICS,Electronic Games,COD,7672
1,B-26055,5729,64,14,FURNITURE,Chairs,EMI,80206
2,B-25955,2927,146,8,FURNITURE,Bookcases,EMI,23416
3,B-26093,2847,712,8,ELECTRONICS,Printers,Credit Card,22776
4,B-25602,2617,1151,4,ELECTRONICS,Phones,Credit Card,10468

Aggregation and Grouping

In [36]:
details_dataset.groupby("Category")["Profit"].mean()

Category
CLOTHING       14.041096
ELECTRONICS    42.733766
FURNITURE      43.111111
Name: Profit, dtype: float64

In [37]:
# Simple average of the whole column
avg_profit = details_dataset["Profit"].mean()
print(avg_profit)

24.642

In [38]:
#COUNT THE NUMBER OF OCCURENCE
payment_counts = details_dataset["PaymentMode"].value_counts()
payment_counts

PaymentMode
COD            684
UPI            331
Debit Card     202
Credit Card    163
EMI            120
Name: count, dtype: int64

In [39]:
# This creates a matrix of Categories vs PaymentModes
pd.crosstab(details_dataset['Category'], details_dataset['PaymentMode'])

PaymentMode  COD  Credit Card  Debit Card  EMI  UPI
Category
CLOTHING     446           89         128   65  221
ELECTRONICS  128           41          47   34   58
FURNITURE    110           33          27   21   52

In [43]:
details_dataset.sort_values(by="Amount",ascending=False).head()#by default in ascending lowest to highest

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Total
1,B-26055,5729,64,14,FURNITURE,Chairs,EMI,80206
1499,B-25993,4363,305,5,FURNITURE,Tables,EMI,21815
1497,B-25973,4141,1698,13,ELECTRONICS,Printers,COD,53833
12,B-25923,3873,-891,6,ELECTRONICS,Phones,Credit Card,23238
1496,B-25757,3151,-35,7,CLOTHING,Trousers,EMI,22057

In [50]:
details_dataset.sort_values(by=["Profit", "Quantity"], ascending=[False, False]).head()

,Order_Id,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Total
59,B-25608,1364,1864,5,FURNITURE,Tables,Credit Card,6820
1497,B-25973,4141,1698,13,ELECTRONICS,Printers,COD,53833
32,B-26022,1824,1303,8,ELECTRONICS,Phones,Credit Card,14592
4,B-25602,2617,1151,4,ELECTRONICS,Phones,Credit Card,10468
1423,B-25601,1275,1148,7,FURNITURE,Bookcases,EMI,8925